### PR TITLE
Improvements to initialValue function support, update to manifests and requesting NPM publish

### PR DESCRIPTION
**Pull request by dominicbarnes**
- `initialValue` function enhancements
  - Now works for multi-dimensional arrays (with tests to prove it)
  - Now provides the coordinates to the function as arguments (with tests)
- Manifest changes:
  - Trying to make the description in the manifest more specific/clear
  - Changed name to `zeroes` (since that is available on NPM)

It would be great to see this published to NPM, since the name `zeroes` is available. :)

### CODE REVIEW

**Comment by reinpk** [comment]
looks awesome!

**Comment by reinpk** [comment]
and we're live :) https://www.npmjs.com/package/zeroes

**Comment by dominicbarnes** [comment]
Sorry to be a pain, but the npm version and duo/component version are out of sync. Could you bump minor, push that new tag and publish again to npm?

Thanks :)

**Comment by reinpk** [comment]
ok it should be `0.1.0` across the board now, good yeah?

**Comment by dominicbarnes** [comment]
Looks great! Thanks :)

**Pull request merged**
